In [1]:
x = 15

In [2]:
type(x)

int

In [3]:
x = [1,2,3]

In [4]:
len(x)

3

In [5]:
x = [[1,2],[2,3],[4,5]]

In [6]:
type(x)

list

In [7]:
len(x)

3

In [8]:
x[0]

[1, 2]

In [9]:
type(x[0])

list

In [10]:
def zeros_matrix(rows,cols):
  result = []
  while len(result) < rows:
    result.append([])
    while len(result[-1]) < cols:
      result[-1].append(0)
  return result

In [11]:
zeros_matrix(3,3)

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]

In [ ]:
lis = []

In [ ]:
lis.append([])

In [ ]:
lis

[[]]

In [ ]:
lis[-1]

[]

In [ ]:
lis[0]

[]

In [ ]:
lis.append([])

In [ ]:
lis

[[], []]

In [ ]:
lis[-1].append(0)

In [ ]:
lis

[[], [0]]

In [ ]:
lis[-1]

[0]

In [ ]:
X = [[25,2,5],[25,2,5],[25,2,5]]
l2_norm_inner = 0
for i in X:
  Y = i
  for j in Y:
    l2_norm_inner = l2_norm_inner + j**2
print(l2_norm_inner)
l2_norm_inner**(1/2)

1962


44.294469180700204

In [ ]:
import numpy as np
X = [[[25,2,5],[25,2,5],[25,2,5]],[[25,2,5],[25,2,5],[25,2,5]],[[25,2,5],[25,2,5],[25,2,5]]]
np.linalg.norm(X)

76.72027111526653

In [ ]:
X_arr = np.array(X)

In [ ]:
X_arr.shape

(3, 3, 3)

In [ ]:
X_arr[0]

array([[25,  2,  5],
       [25,  2,  5],
       [25,  2,  5]])

In [ ]:
X_arr[0][0]

array([25,  2,  5])

In [ ]:
X_arr[0].shape

(3, 3)

In [15]:
def find_mean(X):
  mean_val=0
  if len(X)==0:
    return mean_val
  for i in X:
    mean_val = mean_val + i
  return mean_val/(len(X))

In [17]:
def find_std(X):
  std_value = 0
  variance_value = 0
  for i in X:
    variance_value = variance_value + (i - find_mean(X))**2
  variance_value = variance_value/len(X)
  std_value = variance_value**(1/2)
  return std_value


In [18]:
input = [22,24,26,52,45,37,78,90,110]
find_std(input)

29.980652197256138

In [19]:
import numpy as np
X=[22,24,26,52,45,37,78,90,110]
np.std(X)

29.980652197256138

In [22]:
import numpy as np
#creating matrix from string
A = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print("Array created using string is :\n", A)

Array created using string is :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
type(A)

numpy.matrix